### ISSUE TITLE
Images are not showing in the listing

### ISSUE THREAD

**Issue by danielmessi13** [oguzhnatly/flutter_carplay#5]
|In Readme:|In the built project:|
|--|--|
|![image](https://user-images.githubusercontent.com/29608634/135530703-b09a1c5d-8a47-4eb8-be0f-249c7aa96de8.png)| ![image](https://user-images.githubusercontent.com/29608634/135530264-e5e8cfff-46c7-4d86-ac13-d661e4c1ccbe.png)

## Repositories:

- https://github.com/oguzhnatly/flutter_carplay#readme/blob/master/example/lib/main.dart
- https://github.com/danielmessi13/carplay_test/tree/image_not_show

**Comment by oguzhnatly** [comment]
Hello, @danielmessi13. Thank you for reporting your concern about the bug, and providing your GitHub project repository.

I've tested and ran your project with the `image_not_show` branch, and it works perfectly with the images in the listing --- as you expected. Could you please re-test it by removing and deleting Xcode caches, Flutter project caches, or directly deleting the project and cloning it from your project? Kindly let me know if this does not work for you.
